<?php

namespace Database\Seeders;
use App\Models\Generalsetting;

use Illuminate\Database\Seeder;

class GeneralSettingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Generalsetting::create([
            'logo' => '1564151021logo.png',
            'favicon' => '1566201287output_onlinepngtools_qFA_icon.ico', 
            'title' => 'Online Store', 
            'site' => 'https://www.127.0.0.1:8000', 
            'bgimg' => '1534401824Slider-image3.jpg',
            'cimg' => '1535429167review-bg.jpg', 
            'about' => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae', 
            'street' => 'Office 714 , Saddiq Trade Center Gulberg, Lahore', 
            'phone' => '923424473040', 
            'fax' => '', 
            'email' => 'info@127.0.0.1:8000', 
            'footer' => 'COPYRIGHT 2019 Itplanet', 
            'bg_link' => 'Lorem ipsum dolor sit amet',
            'bg_title' => 'https://itplanetsoftware.com/',
            'bg_text' => 'Lorem ipsum dolor sit amet,',
            'np' => '0',
            'fp' => '10',
            'pb' => 'ciit104@gmail.com',
            'sk' => 'pk_test_UnU1Coi1p5qFGwtpjZMRMgJM',
            'ss' => 'sk_test_QQcg3vGsKRPlW6T3dXcNJsor',
            'vid' => 'https://www.youtube.com/watch?v=_sI_Ps7JSEk',
            'vidimg' => '1535432669video-bg.jpg',
            'tags' => 'a,b,c,d,x,y,z,k',
            'sign' => '0',
            'slider' => '1',
            'category' => '1',
            'sb' => '1',
            'hv' => '1',
            'ftp' => '1',
            'lp' => '1',
            'pp' => '0',
            'lb' => '1',
            'bs' => '1',
            'ts' => '1',
            'bl' => '1',
            'ship' => '5',
            'mmi' => '<span style="font-weight: 700; margin: 0px; padding: 0px; border: 0px; vertical-align: baseline; text-size-adjust: none; font-family: Raleway, sans-serif;">Faites vos depots sur les numero suivant 42784249 / 78939896 / 04835863</span>',
            'bi' => '<span style="font-weight: 700; margin: 0px; padding: 0px; border: 0px; vertical-align: baseline; text-size-adjust: none; font-family: Raleway, sans-serif;">Bank Compte Bancaire</span>',
            'pcheck' => '1',
            'scheck' => '1',
            'mcheck' => '0',
            'bcheck' => '0',
            'ccheck' => '0',
            'colors' => '#0057ff',
            'bimg' => '1539851805images.JPG',
            'loader' => '15455007811534395815Blocks-1s-125px.gif',
            'count_title' => 'Deal of The Day',
            'count_heading' => 'GET UP TO 50% OFF',
            'count_date' => '2019/03/28',
            'count_link' => 'https://www.google.com/',
            'count_image' => '1536044322countdown-cover.jpg',
            'order_title' => '<h1 class="text-center" style="font-family: Rubik, sans-serif; font-weight: 500; color: green;">Congratulation !!</h1>',
            'order_text' => '<h2 style="font-family: Rubik, sans-serif; font-weight: 500; color: rgb(51, 51, 51); font-size: 36px; text-align: center;">Your Order Has been Confirmed.</h2>',
            'cart_success' => 'Successfully Added To Cart.',
            'cart_error' => 'Out Of Stock !!',
            'wish_success' => 'Successfully Added To Wishlist.',
            'wish_error' => 'Already Added To Wishlist !!',
            'wish_remove' => 'Successfully Remove From Wishlist.',
            'invalid' => 'Invalid Input !!',
            'color_change' => 'Color has Changed Successfully.',
            'size_change' => 'Size Has Changed Successfully.',
            'coupon_found' => 'Coupon Applied Successfully',
            'no_coupon' => 'No Coupon Found.',
            'coupon_already' => 'This Coupon Has Already Been Applied.',
            'withdraw_charge' => '5',
            'withdraw_fee' => '5',
            'fixed_commission' => '3',
            'percentage_commission' => '5',
            'frenchise_commision' => '0',
            'partner_commision' => '0',
            'tax' => '10',
            'ship_info' => '1',
            'multiple_ship' => '1',
            'is_talkto' => '0',
            'talkto' => '',
            'subscribe_title' => 'NEWSLETTER',
            'subscribe_text' => 'Please subscribe us to get new greatest deals!',
            'subscribe_image' => '156620567611.jpg',
            'is_subscribe' => '0',
            'is_language' => '1',
            'reg_vendor' => '1',
            'rtl' => '0',
            'is_affilate' => '1',
            'affilate_charge' => '0',
            'compare_success' => 'Successfully Added To Compare.',
            'compare_error' => 'Already Added To Compare !!',
            'compare_remove' => 'Successfully Remove From Compare.',
            'guest_checkout' => '1',
            'affilate_banner' => '15455529221538057747banner-2.jpg',
            'smtp_host' => 'in-v3.mailjet.com', 
            'smtp_port' => '587', 
            'smtp_user' => '0e05029e2dc70da691aa2223aa53c5be', 
            'smtp_pass' => '5df1b6242e86bce602c3fd9adc178460', 
            'from_email' => 'admin@geniusocean.com',
             'from_name' => 'LyLy',
             'is_smtp' => '1',
             'is_comment' => '1',
             'footer_background' => '1545561002footer-bg.jpg',
             'is_loader' => '0',
        ]);
    }
}
